# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: acitons/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          
      - name: install dependencies
        run: yarn install
      
      - name: run lint
        run: yarn lint
        
